corewar/corewar

.gitignore
Corewar/Presentation/CoreRenderer.ts
Corewar/Presentation/Presenter.ts
Corewar/Simulator/Defaults.ts
Corewar/Simulator/Simulator.ts
Corewar/app.ts
Corewar/bundle.js
Corewar/index.html
Corewar/tsconfig.json
package-lock.json
package.json
webpack.config.js

`npm init`ed and added webpack, ts-loader and webpack-dev-server 
Builds the .ts files to bundle.js and updated html to use this.
#Disclaimer# Whilst it builds, app doesn't work!

Add webpack npm

---

Corewar/Simulator/Core.ts
Parser.tests/Tests/AddressModPassTests.ts
Simulator.tests/References.ts
Simulator.tests/Tests/CoreTests.ts
package-lock.json
package.json
spec/support/jasmine.json

Added jasmine and jasmine-ts to run the .ts tests as is.
Seems to be some reference issues, to just ran one of the files with explicit imports (ESLint in vscode was my friend).
```
c:\github\gareththegeek\corewar>npm test
> corewar@1.0.0 test c:\github\gareththegeek\corewar
> jasmine-ts
Started
...........
11 specs, 0 failures
Finished in 0.053 seconds
```

Added jasmine and jasmine-ts to test one of the tests

---

package-lock.json
package.json
simulator/tests/ExecutiveTests.ts
simulator/tests/References.ts

Worked out what the problem was, the interface in the internal namespace declaration wasn't exported, results:

Fix jasmine custom matcher 

---

index.ts
package-lock.json
package.json
simulator/tests/ExecutiveTests.ts
simulator/tests/References.ts
simulator/tests/toEqualInstruction.d.ts

Finally fixed it!
https://github.com/TypeStrong/ts-node/issues/462

Fix the `toEqualInstruction` matcher issue

---

index.ts
package-lock.json
package.json
simulator/Core.ts
simulator/interface/ICore.ts

This add's the worlds most basic pubsub mechanism via sort of DI.
To be discussed as to how best to handle this.

Add pubsub

---

simulator/Warrior.ts

Remove unneccesary instruction array from Warrior class - see #41

Remove unnecessary instruction array from Warrior

---

index.ts
package-lock.json
package.json

This removed the limitation on only having one warrior sent to the simulator

Allow multiple warriors

---

corewar/presentation/Presenter.ts
index.d.ts
index.ts
package-lock.json
package.json
simulator/Core.ts
simulator/EndCondition.ts
simulator/Simulator.ts
simulator/interface/ICore.ts
simulator/interface/IEndCondition.ts
simulator/interface/ISimulator.ts

Exposes the run method and tweaks it to return a promise.

Expose run method

---

corewar/app.ts
index.ts
parser/Parser.ts
parser/integration/tests/TestHelper.ts
parser/tests/ParserTests.ts

Fix 66 metadata

---

index.ts
simulator/OptionValidator.ts
simulator/Simulator.ts
simulator/interface/IOperand.ts
simulator/interface/IOptionValidator.ts
simulator/tests/ExecutiveTests.ts
simulator/tests/FetcherTests.ts
simulator/tests/OptionValidatorTests.ts
simulator/tests/SimulatorTests.ts

Resolve #68 by throwing an error when presented with invalid options

Fix 68 validate options

---

simulator/Loader.ts
simulator/Warrior.ts
simulator/WarriorLoader.ts
simulator/interface/IWarrior.ts
simulator/interface/IWarriorLoader.ts
simulator/tests/CoreTests.ts
simulator/tests/DataHelper.ts
simulator/tests/EndConditionTests.ts
simulator/tests/LoaderTests.ts
simulator/tests/WarriorLoaderTests.ts

Assign unique ids to warriors

---

package-lock.json
package.json
simulator/Core.ts
simulator/EndCondition.ts
simulator/Simulator.ts
tsconfig.json

Update settings to build to es5
Fix progress reporting function to do correct maths!
Make pubsub use sync methods so it completes in a sensible time,

Build to es5

---

simulator/Core.ts
simulator/tests/CoreTests.ts

Reintroduce execute core access event

---

package-lock.json
package.json
simulator/Core.ts
simulator/Defaults.ts
simulator/Fetcher.ts
simulator/Simulator.ts
simulator/interface/ICore.ts
simulator/interface/IFetcher.ts
simulator/interface/IState.ts
simulator/tests/CoreTests.ts
simulator/tests/EndConditionTests.ts
simulator/tests/ExecutiveTests.ts
simulator/tests/FetcherTests.ts
simulator/tests/OptionValidatorTests.ts
simulator/tests/SimulatorTests.ts

Clone data

---

package-lock.json
package.json
simulator/Core.ts
simulator/Fetcher.ts
simulator/Simulator.ts
simulator/tests/SimulatorTests.ts
wercker.yml

Fix for #86 
Early out of step function if end condition met

Task undefined bug 86

---

simulator/WarriorLoader.ts
simulator/tests/WarriorLoaderTests.ts

Load process before loading instruction into core

---

parser/integration/tests/TestHelper.ts
parser/integration/tests/TestLoader.ts

Wrap file accesses in a promise

---

package-lock.json
package.json
wercker.yml

Auto npm publish

---

index.ts
wercker.yml

Also expose getAt specifically

tweak wercker publish step

---

package-lock.json
package.json
wercker.yml

Expose get at

---

simulator/Publisher.ts
simulator/Simulator.ts
simulator/interface/IMessage.ts
simulator/interface/IPublisher.ts
simulator/interface/ISimulator.ts
simulator/tests/CoreTests.ts
simulator/tests/EndConditionTests.ts
simulator/tests/ExecutiveTests.ts
simulator/tests/PublisherTests.ts
simulator/tests/SimulatorTests.ts

`simulator.run` will now only produce ROUND_END messages

Disable messages during run

---

index.ts
package-lock.json
simulator/Core.ts
simulator/interface/ICore.ts
simulator/interface/ICoreLocation.ts
simulator/tests/CoreTests.ts
simulator/tests/DecoderTests.ts
simulator/tests/ExecutiveTests.ts
simulator/tests/FetcherTests.ts
simulator/tests/LoaderTests.ts
simulator/tests/SimulatorTests.ts
simulator/tests/WarriorLoaderTests.ts

Add `getWithInfoAt` method to `ICore` to return both the `IInstruction` and the `AccessEventArgs` for the specified address.  This could be further enhanced to return the serialised version of the `IInstruction` to the UI.

Store access events in core

---

simulator/EndCondition.ts
simulator/tests/EndConditionTests.ts

Change max cycle comparison to greater than or equal

---

simulator/WarriorLoader.ts
simulator/tests/WarriorLoaderTests.ts

Should resolve #83 - initial core colours

Assign warrior id before writing instructions to core

---

simulator/Executive.ts
simulator/tests/ExecutiveTests.ts

Fix the hole in the ring! #101

Use maxTasks not instructionLimit

---

index.ts
simulator/Simulator.ts

Ensure defaults are handled correctly 
https://github.com/gareththegeek/corewar-ui/issues/134

Fix 134 hanging on finish click

---

index.ts
simulator/WarriorLoader.ts
simulator/tests/WarriorLoaderTests.ts

Loader task count message 140

---

package-lock.json
package.json
simulator/Core.ts
simulator/tests/CoreTests.ts

No dat exec message 136

---

parser/LabelCollector.ts
parser/integration/tests/ICWS-94Tests.ts
parser/tests/LabelCollectorTests.ts

Labels on own line 137

---

parser/Scanner.ts
parser/tests/ScannerTests.ts

Allow colons 138

---

package-lock.json
package.json

npm publish

---

package.json
tsconfig.json
typings/index.d.ts

Manually declare the typings for the project as I have totally failed to get typescript to do it for me

Use manual typings

---

package.json
src/index.ts
typings/index.d.ts

* Hill Runner is now included in Api (so it's actually calleable)
* `step` `run` `runMatch` and `runHill` now return results in addition to publishing messages
* Up-version 0.1.7

Add hill runner to api and add more return values from Api

---

src/simulator/Executive.ts
src/simulator/interface/IMessage.ts
test/simulator/unit/ExecutiveTestHelper.ts
test/simulator/unit/ExecutiveTests.ts

Queue WarriorDead message when warrior's task count is reduced to zero
